# Generated by Django 2.0 on 2018-04-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anews',
            name='main_image',
            field=models.ImageField(default=None, upload_to='news_image'),
        ),
    ]
