# Generated by Django 2.0 on 2018-04-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180410_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anews',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='news_image/%Y/%m/%d'),
        ),
    ]
