# Generated by Django 2.0 on 2018-04-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180411_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anews',
            options={'ordering': ['-created_time']},
        ),
    ]
