# Generated by Django 2.0 on 2018-04-16 12:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180416_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anews',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
