# Generated by Django 2.0 on 2018-04-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180416_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='anews',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
