# Generated by Django 2.0 on 2018-04-19 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_anews_read_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='anews',
            name='read_num',
        ),
        migrations.AlterField(
            model_name='anews',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='readnum',
            name='news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='news.Anews'),
        ),
    ]
