# Generated by Django 2.0 on 2018-04-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20180419_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='news',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
