# Generated by Django 2.0 on 2018-04-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20180419_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anews',
            name='main_image',
        ),
    ]
