# Generated by Django 2.0 on 2018-04-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180426_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='commment',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
