# Generated by Django 2.0 on 2018-04-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_commment_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commment',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='commment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comment.Commment'),
        ),
    ]
